### ISSUE TITLE
XP Release: "Error: Invalid Arguments. Run iquecrypt with -h or --"

### ISSUE THREAD

**Issue by catsinabucket** [jbop1626/iquecrypt#1]
Running the XP release on a VirtualBox VM, and I'm getting this error upon startup. It took a while to capture as the command prompt closes as fast as it opens.

I'm not too well versed with using command prompt, so would you possibly be able to provide some assistance with working around this?

Thanks in advance :)

EDIT: Worked out how to run it using "-h", but unsure as to where to go from here. I'm starting from total scratch with the aim of being in a position where I can inject a game. Any help would be appreciated if possible

**Comment by jbop1626** [comment]
It sounds like you already figured out that you need to run the program from command prompt and not just double-click, but if not let me know and I can link some stuff to explain it.  

The first steps are to dump your console's NAND with [iQueDiagExtend](https://github.com/emoose/iQueDiagExtend), some instructions for which you can find [here](http://www.iquebrew.org/index.php?title=IQueDiagExtend) (you need the official software iQue@Home installed too). Then you want to extract files from your NAND with [iQueTool](https://github.com/emoose/iQueTool/releases); you should be able to just use the nand_extract.bat file for that, after making sure the NAND dump is named simply "nand.bin". Last time I used iQueTool I had some trouble getting the newest release to run, so if you have problems try using an older release.  

After doing those steps you should have files you can work with, like apps, ticket.sys, and recrypt.sys. However, some functions of iQueCrypt require a [Virage2](http://www.iquebrew.org/index.php?title=Virage2) dump, including injection. Currently I don't think there are any complete, public tools to do that which I can link to. That should change soon enough.  

After that, check out the [usage manual](https://github.com/jbop1626/iquecrypt/blob/master/USAGE.md) (which has the actual command syntax) and the [iQueCrypt page on iQueBrew](http://www.iquebrew.org/index.php?title=IQueCrypt), as well as the rest of iQueBrew to help understand what keys are what, etc.  

I'll also add some more detailed instructions for specific operations to the iQueCrypt page soon.

**Comment by Jhynjhiruu** [comment]
Hopefully we'll have a proper guide out soon, but for now if you can find the iQueBrew Discord server we can help you there.

**Comment by catsinabucket** [comment]
That's fantastic! Thank you very much for all the information, it's just what I needed!

I've dumped my nand.bin (and spare.bin), and I'll try and get that extracted with iQueTool. Like you said, I've also had some trouble with the latest release (not sure of the exact message, I'll get that after work today), so I'll try an older release and see if that works alright.

Thank you again for your help, it's much appreciated. I'll seek out the Discord server when I can.

**Comment by jbop1626** [comment]
@catsinabucket A likely easier alternative: if you can find the Ocarina of Time speedrunning discord, you should be able to find a "certain someone" in the mod list who can give you a link to the iQueBrew one.

**Comment by jbop1626** [comment]
Closing since you were able to find us!
